on:
  pull_request:

name: Continuous integration

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
        device:
          - stm32f334x4
          - stm32f334x6
          - stm32f334x8

          #- stm32h742
          #- stm32h743
          ##- stm32h745
          ##- stm32h747
          #- stm32h750
          #- stm32h753
          ##- stm32h755
          ##- stm32h757

          - stm32g474
          - stm32g484
        features:
          - defmt

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: thumbv7em-none-eabihf
          override: true

      - name: Regular build
        run: cargo check --features ${{ matrix.device }} --features ${{ matrix.features }}
      - name: Build examples
        run: cargo check --examples --features ${{ matrix.device }} --features ${{ matrix.features }}
      - name: Clippy
        run: cargo clippy --examples --features ${{ matrix.device }} --features ${{ matrix.features }}
